spring.application.name=payment-service
spring.config.import=configserver:http://localhost:8888


server.port=8086

#stripe.secretKey =sk_test_51RW9RvPqI4I83QHYYK6o7bRPfUxM070CmnoKUSd23048GoZVclzRUmC8poV8rKD20zeXnSLgzblVhwGT6DbGYQKF00zhPRxhaM


spring.datasource.url=jdbc:mysql://localhost:3306/payment_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Optional: To show host info in Eureka UI
eureka.instance.hostname=localhost

# Optional: Prevent registration conflicts in dev environment
eureka.instance.prefer-ip-address=true

# RabbitMQ queue name
payment.queue.name=payment_queue


# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Custom RabbitMQ settings
rabbitmq.exchange=payment.exchange
rabbitmq.queue=order.payment.queue
rabbitmq.routingkey=payment.success
