# ========== App Info ==========
spring.application.name=farmer-service
logging.level.root=DEBUG

# Extra logging for Eureka registration
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG


# Logging configuration for FarmerService

logging.file.name=logs/farmer-service.log

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Optional: To show host info in Eureka UI
eureka.instance.hostname=localhost

# Optional: Prevent registration conflicts in dev environment
eureka.instance.prefer-ip-address=true

server.port=8080

# JWT shared secret key (must match the one used in Authentication Service)


# ========== MySQL Config ==========
spring.datasource.url=jdbc:mysql://localhost:3306/farmerdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

spring.security.user.name = naincy
spring.security.user.password = nain@123

# ========== JPA Settings ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ========== Logging (Optional) ==========
logging.level.org.hibernate.SQL=DEBUG


# App-level logging
logging.level.com.cropdeal.farmer_service=DEBUG