spring.application.name=api-gateway-service
server.port=8084


spring.main.web-application-type=reactive

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Spring Cloud Gateway Routes Configuration
spring.cloud.gateway.routes[0].id=farmer-service
spring.cloud.gateway.routes[0].uri=lb://farmer-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/farmers/**

spring.cloud.gateway.routes[1].id=dealer-service
spring.cloud.gateway.routes[1].uri=lb://dealer-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/dealers/**

spring.cloud.gateway.routes[2].id=cropservice
spring.cloud.gateway.routes[2].uri=lb://cropservice
spring.cloud.gateway.routes[2].predicates[0]=Path=/crops/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2

spring.cloud.gateway.routes[3].id=authentication-service
spring.cloud.gateway.routes[3].uri=lb://authentication-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=lb://order-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/orders/**


spring.cloud.gateway.routes[5].id=admin-service
spring.cloud.gateway.routes[5].uri=lb://admin-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/Admin/**

jwt.secret=v87f21uzR8BoL63GmpYYGVR7EaSuIJ71RuGF0EZRW4uACvvUwM6OigKoob0r8fg/

#spring.security.oauth2.resourceserver.jwt.secret-key=v87f21uzR8BoL63GmpYYGVR7EaSuIJ71RuGF0EZRW4uACvvUwM6OigKoob0r8fg/



# Optional: Set timeouts or filters (for example)
# spring.cloud.gateway.default-filters[0]=AddRequestHeader=X-Request-Foo, Bar
# spring.cloud.gateway.default-filters[1]=AddResponseHeader=X-Response-Foo, Baz